# Generated by Django 4.2.2 on 2023-09-11 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newborn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('start_dose_time', models.TimeField()),
                ('second_dose_time', models.TimeField(blank=True, null=True)),
                ('third_dose_time', models.TimeField(blank=True, null=True)),
                ('fourth_dose_time', models.TimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('Once Daily', 'Once Daily'), ('Twice Daily', 'Twice Daily'), ('Three Times Daily', 'Three Times Daily'), ('Four Times Daily', 'Four Times Daily')], max_length=20)),
                ('start_date', models.DateField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='newborn.newbornadmission')),
                ('prescriber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_prescribed2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dose4Dispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensation_datetime', models.DateTimeField(auto_now_add=True)),
                ('dose4_status', models.CharField(choices=[('Pending', 'Pending'), ('Given', 'Given'), ('Missed', 'Missed')], max_length=15)),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose4_dispensations_given', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose4_dispensations', to='treatment.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Dose3Dispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensation_datetime', models.DateTimeField(auto_now_add=True)),
                ('dose3_status', models.CharField(choices=[('Pending', 'Pending'), ('Given', 'Given'), ('Missed', 'Missed')], max_length=15)),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose3_dispensations_given', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose3_dispensations', to='treatment.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Dose2Dispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensation_datetime', models.DateTimeField(auto_now_add=True)),
                ('dose2_status', models.CharField(choices=[('Pending', 'Pending'), ('Given', 'Given'), ('Missed', 'Missed')], max_length=15)),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose2_dispensations_given', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose2_dispensations', to='treatment.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Dose1Dispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensation_datetime', models.DateTimeField(auto_now_add=True)),
                ('dose1_status', models.CharField(choices=[('Pending', 'Pending'), ('Given', 'Given'), ('Missed', 'Missed')], max_length=15)),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose1_dispensations_given', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose1_dispensations', to='treatment.prescription')),
            ],
        ),
    ]
