# Generated by Django 3.2.18 on 2023-03-24 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=28)),
                ('blood_group', models.CharField(choices=[('A+', 'A RhD+'), ('B+', 'B RhD+'), ('AB+', 'AB RhD+'), ('O+', 'O RhD+'), ('A-', 'A RhD-'), ('B-', 'B RhD-'), ('AB-', 'AB RhD-'), ('O-', 'O RhD-')], max_length=3)),
                ('parity', models.CharField(max_length=100)),
                ('number_of_living_children', models.CharField(max_length=100)),
                ('hiv_status', models.CharField(choices=[('NEG', 'Negative'), ('POS', 'Positive'), ('UNS', 'Not sure')], max_length=3)),
                ('level_of_education', models.CharField(choices=[('PR', 'Primary'), ('SR', 'Secondary'), ('DP', 'Diploma'), ('BA', 'Bachelors Degree'), ('MA', 'Masters')], max_length=2)),
                ('occupation', models.CharField(choices=[('HW', 'Health Worker'), ('TR', 'Teacher'), ('LW', 'Lawyer'), ('AC', 'Accountant'), ('BU', 'Business'), ('FMR', 'Farmer'), ('ENG', 'Engineer'), ('SW', 'Social Worker'), ('OTH', 'Other')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MotherLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('subcounty', models.CharField(max_length=100)),
                ('parish', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('nin_no', models.CharField(default='CMX10000000', max_length=100)),
                ('contact', models.CharField(default='+256 ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Newborn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('birth_weight', models.DecimalField(decimal_places=2, max_digits=2)),
                ('admission_date', models.DateField()),
                ('age_in_days', models.IntegerField(default=0)),
                ('gestation_age', models.IntegerField(default=28)),
                ('diagnosis', models.CharField(max_length=100)),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newborn.motherdetails')),
            ],
            options={
                'ordering': ['admission_date'],
            },
        ),
        migrations.AddField(
            model_name='motherdetails',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newborn.motherlocation'),
        ),
        migrations.CreateModel(
            name='LabInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serology', multiselectfield.db.fields.MultiSelectField(choices=[('RPR', 'RPR'), ('RCT', 'RCT'), ('BAT', 'BAT')], max_length=100)),
                ('microbiology', multiselectfield.db.fields.MultiSelectField(choices=[('Gram stain', 'Gram stain'), ('Culture', 'Culture')], max_length=100)),
                ('chemistry', multiselectfield.db.fields.MultiSelectField(choices=[('Serum electrolytes', 'Serum electrolytes'), ('Serum Urea', 'Serum Urea'), ('Serum creatinine', 'Serum creatinine'), ('Urinalysis', 'Urinalysis')], max_length=100)),
                ('hematology', multiselectfield.db.fields.MultiSelectField(choices=[('CBC', 'CBC'), ('Blood grouping', 'Blood grouping')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
