# Generated by Django 3.2.18 on 2023-03-30 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=28)),
                ('blood_group', models.CharField(choices=[('A+', 'A RhD+'), ('B+', 'B RhD+'), ('AB+', 'AB RhD+'), ('O+', 'O RhD+'), ('A-', 'A RhD-'), ('B-', 'B RhD-'), ('AB-', 'AB RhD-'), ('O-', 'O RhD-')], max_length=50)),
                ('parity', models.CharField(max_length=100)),
                ('number_of_living_children', models.CharField(max_length=100)),
                ('hiv_status', models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('Not sure', 'Not sure')], max_length=50)),
                ('level_of_education', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Diploma', 'Diploma'), ('Bachelors Degree', 'Bachelors Degree'), ('Masters', 'Masters')], max_length=50)),
                ('occupation', models.CharField(choices=[('Health Worker', 'Health Worker'), ('Teacher', 'Teacher'), ('Lawyer', 'Lawyer'), ('Accountant', 'Accountant'), ('Business', 'Business'), ('Farmer', 'Farmer'), ('Engineer', 'Engineer'), ('Social Worker', 'Social Worker'), ('Other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MotherLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('subcounty', models.CharField(max_length=100)),
                ('parish', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('nin_no', models.CharField(default='CMX10000000', max_length=100)),
                ('contact', models.CharField(default='+256 ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Newborn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=100)),
                ('birth_weight', models.DecimalField(decimal_places=1, max_digits=2)),
                ('delivery_date', models.DateTimeField()),
                ('place_of_birth', models.CharField(choices=[('Hospital', 'Hospital'), ('Home', 'Home'), ('Along the road', 'Along the road')], max_length=100)),
                ('mode_of_delivery', models.CharField(choices=[('Vaginal', 'Vaginal'), ('C-Section', 'C-Section'), ('Assisted Vaginal Delivery', 'Assisted Vaginal Delivery')], max_length=100)),
                ('resuscitated', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('referral', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newborn.motherdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(blank=True)),
                ('general_findings', models.TextField(blank=True)),
                ('respiratory_findings', models.TextField(blank=True)),
                ('cardiovascular_findings', models.TextField(blank=True)),
                ('abdominal_findings', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewbornExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=2)),
                ('respiratory_rate', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('skin_color', models.CharField(max_length=100)),
                ('general_appearance', models.CharField(max_length=100)),
                ('head_and_neck', models.CharField(max_length=100)),
                ('chest', models.CharField(max_length=100)),
                ('abdomen', models.CharField(max_length=100)),
                ('genitalia', models.CharField(max_length=100)),
                ('extremities', models.CharField(max_length=100)),
                ('neurological_exam', models.CharField(max_length=100)),
                ('neonate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newborn.newborn')),
            ],
        ),
        migrations.AddField(
            model_name='motherdetails',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newborn.motherlocation'),
        ),
        migrations.CreateModel(
            name='LabInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serology', multiselectfield.db.fields.MultiSelectField(choices=[('RPR', 'RPR'), ('RCT', 'RCT'), ('BAT', 'BAT')], max_length=100)),
                ('microbiology', multiselectfield.db.fields.MultiSelectField(choices=[('Gram stain', 'Gram stain'), ('Culture', 'Culture')], max_length=100)),
                ('chemistry', multiselectfield.db.fields.MultiSelectField(choices=[('Serum electrolytes', 'Serum electrolytes'), ('Serum Urea', 'Serum Urea'), ('Serum creatinine', 'Serum creatinine'), ('Urinalysis', 'Urinalysis')], max_length=100)),
                ('hematology', multiselectfield.db.fields.MultiSelectField(choices=[('CBC', 'CBC'), ('Blood grouping', 'Blood grouping')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
