# Generated by Django 4.2.2 on 2023-07-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newborn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbornadmission',
            name='reason_for_referral',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
