# Generated by Django 4.2.2 on 2023-07-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newborn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='subcounty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newborn.subcounty'),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newborn.district'),
        ),
        migrations.AlterField(
            model_name='village',
            name='parish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newborn.parish'),
        ),
    ]
