# Generated by Django 4.1.3 on 2022-12-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newborn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherdetails',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newborn.motherlocation'),
        ),
        migrations.AlterField(
            model_name='newborn',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newborn.motherdetails'),
        ),
    ]
