# Generated by Django 4.2.2 on 2023-08-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newborn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensation',
            name='dose1_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Given', 'Given'), ('Missed', 'Missed')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='dose2_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Given', 'Given'), ('Missed', 'Missed')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='dose3_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Given', 'Given'), ('Missed', 'Missed')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='dose4_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Given', 'Given'), ('Missed', 'Missed')], max_length=15, null=True),
        ),
    ]
