# Generated by Django 4.2.2 on 2023-07-05 10:54

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newborn', '0002_antenatalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinvestigation',
            name='neonate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newborn.newborn'),
        ),
        migrations.AlterField(
            model_name='labinvestigation',
            name='chemistry',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Serum electrolytes', 'Serum electrolytes'), ('Serum Urea', 'Serum Urea'), ('Serum creatinine', 'Serum creatinine'), ('Urinalysis', 'Urinalysis')], max_length=100),
        ),
        migrations.AlterField(
            model_name='labinvestigation',
            name='hematology',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CBC', 'CBC'), ('Blood grouping', 'Blood grouping')], max_length=100),
        ),
        migrations.AlterField(
            model_name='labinvestigation',
            name='microbiology',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Gram stain', 'Gram stain'), ('Culture', 'Culture')], max_length=100),
        ),
        migrations.AlterField(
            model_name='labinvestigation',
            name='serology',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('RPR', 'RPR'), ('RCT', 'RCT'), ('BAT', 'BAT')], max_length=100),
        ),
    ]
