# Generated by Django 4.2.2 on 2023-07-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newborn', '0002_mothersantenataldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='mothersantenataldetails',
            name='facility_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
