# Generated by Django 3.2.18 on 2023-03-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newborn', '0002_alter_newborn_birth_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(blank=True)),
                ('general_findings', models.TextField(blank=True)),
                ('respiratory_findings', models.TextField(blank=True)),
                ('cardiovascular_findings', models.TextField(blank=True)),
                ('abdominal_findings', models.TextField(blank=True)),
            ],
        ),
    ]
