# Generated by Django 3.2.18 on 2023-03-21 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newborn', '0002_alter_motherdetails_location_alter_newborn_mother'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serology', models.CharField(blank=True, choices=[('RPR', 'RPR'), ('RCT', 'RCT'), ('BAT', 'BAT')], max_length=3, null=True)),
                ('microbiology', models.CharField(blank=True, choices=[('Gram stain', 'Gram stain'), ('Culture', 'Culture')], max_length=20, null=True)),
                ('chemistry', models.CharField(blank=True, choices=[('Serum electrolytes', 'Serum electrolytes'), ('Serum Urea', 'Serum Urea'), ('Serum creatinine', 'Serum creatinine'), ('Urinalysis', 'Urinalysis')], max_length=20, null=True)),
                ('hematology', models.CharField(blank=True, choices=[('CBC', 'CBC'), ('Blood grouping', 'Blood grouping')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
