# Generated by Django 4.2.2 on 2023-07-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newborn', '0003_mothersantenataldetails_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mothersantenataldetails',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newborn.motherdetails'),
        ),
    ]
