# Generated by Django 4.2.2 on 2023-08-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newborn', '0003_alter_labresult_serology_rct_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newborn.newbornadmission')),
            ],
        ),
    ]
