# Generated by Django 3.2.18 on 2023-03-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newborn', '0003_labinvestigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labinvestigation',
            name='chemistry',
            field=models.CharField(blank=True, choices=[('Serum electrolytes', 'Serum electrolytes'), ('Serum Urea', 'Serum Urea'), ('Serum creatinine', 'Serum creatinine'), ('Urinalysis', 'Urinalysis')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labinvestigation',
            name='hematology',
            field=models.CharField(blank=True, choices=[('CBC', 'CBC'), ('Blood grouping', 'Blood grouping')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labinvestigation',
            name='microbiology',
            field=models.CharField(blank=True, choices=[('Gram stain', 'Gram stain'), ('Culture', 'Culture')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labinvestigation',
            name='serology',
            field=models.CharField(blank=True, choices=[('RPR', 'RPR'), ('RCT', 'RCT'), ('BAT', 'BAT')], max_length=100, null=True),
        ),
    ]
