# Generated by Django 3.2.18 on 2023-03-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newborn', '0003_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_birth', models.CharField(choices=[('Home', 'Home'), ('Health Facility', 'Health Facility'), ('Road side', 'Road side')], max_length=20)),
                ('name_of_health_facility', models.CharField(blank=True, max_length=100, null=True)),
                ('location_of_health_facility', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_of_delivery', models.CharField(choices=[('Ceaserean section', 'Ceaserean section'), ('SVD', 'SVD'), ('Assisted Delivery', 'Assisted Delivery')], max_length=20)),
                ('indication_for_csection', models.CharField(blank=True, choices=[('Preeclampsia', 'Preeclampsia'), ('Preterm labour', 'Preterm labour')], max_length=20, null=True)),
                ('time_btn_cs_and_delivery', models.CharField(blank=True, choices=[('less than 30min', 'less than 30min'), ('30min to 1 hour', '30min to 1 hour'), ('more than 1 hour', 'more than 1 hour')], max_length=20, null=True)),
                ('resuscitation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('length_of_resuscitation', models.CharField(blank=True, choices=[('less than 10min', 'less than 10min'), ('btn 10min to 15 min', 'btn 10min to 15 min'), ('more than 15min', 'more than 15min')], max_length=30, null=True)),
                ('was_ox_connected', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('referral', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('reason_for_referral', models.CharField(blank=True, max_length=100, null=True)),
                ('date_and_time_of_referral', models.DateTimeField(blank=True, null=True)),
                ('mean_of_transport', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
