# Generated by Django 4.2.2 on 2023-08-20 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newborn', '0004_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dispenser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_dispensed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_prescribed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(choices=[('Once Daily', 'Once Daily'), ('Twice Daily', 'Twice Daily'), ('Three Times Daily', 'Three Times Daily'), ('Four Times Daily', 'Four Times Daily')], max_length=20),
        ),
    ]
