# Generated by Django 4.2.2 on 2023-09-11 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newborn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('serology_rpr_requested', models.BooleanField(default=False, verbose_name='RPR')),
                ('serology_rct_requested', models.BooleanField(default=False, verbose_name='RCT')),
                ('serology_bat_requested', models.BooleanField(default=False, verbose_name='BAT')),
                ('microbiology_gram_stain_requested', models.BooleanField(default=False, verbose_name='Gram stain')),
                ('microbiology_culture_requested', models.BooleanField(default=False, verbose_name='Culture')),
                ('chemistry_serum_electrolytes_requested', models.BooleanField(default=False, verbose_name='Serum electrolytes')),
                ('chemistry_serum_urea_requested', models.BooleanField(default=False, verbose_name='Serum Urea')),
                ('chemistry_serum_creatinine_requested', models.BooleanField(default=False, verbose_name='Serum creatinine')),
                ('chemistry_urinalysis_requested', models.BooleanField(default=False, verbose_name='Urinalysis')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to=settings.AUTH_USER_MODEL)),
                ('neonate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='newborn.newbornadmission')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serology_rpr_result', models.CharField(blank=True, max_length=100, null=True, verbose_name='RPR')),
                ('serology_rct_result', models.CharField(blank=True, max_length=100, null=True, verbose_name='RCT')),
                ('serology_bat_result', models.CharField(blank=True, max_length=100, null=True)),
                ('microbiology_gram_stain_result', models.CharField(blank=True, max_length=100, null=True)),
                ('microbiology_culture_result', models.CharField(blank=True, max_length=100, null=True)),
                ('chemistry_serum_electrolytes_result', models.CharField(blank=True, max_length=100, null=True)),
                ('chemistry_serum_urea_result', models.CharField(blank=True, max_length=100, null=True)),
                ('chemistry_serum_creatinine_result', models.CharField(blank=True, max_length=100, null=True)),
                ('chemistry_urinalysis_result', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to=settings.AUTH_USER_MODEL)),
                ('lab_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.labrequest')),
                ('neonate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='newborn.newbornadmission')),
            ],
        ),
    ]
