# Generated by Django 4.2.2 on 2023-10-18 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('head_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('respiration', models.PositiveIntegerField(blank=True, null=True)),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('muac', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('oxygen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('datetime_taken', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.registration')),
            ],
        ),
    ]
